// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScontrinoSaga.Data;

#nullable disable

namespace ScontrinoSaga.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240705122213_Invoice double ")]
    partial class Invoicedouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("ScontrinoSaga.Data.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceGUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("InvoiceGrandTotal")
                        .HasColumnType("REAL");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ScontrinoSaga.Data.InvoiceRow", b =>
                {
                    b.Property<int>("InvoiceRowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("InvoiceRowPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("InvoiceRowProductProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceRowQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentInvoiceInvoiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceRowID");

                    b.HasIndex("InvoiceRowProductProductID");

                    b.HasIndex("ParentInvoiceInvoiceId");

                    b.ToTable("InvoicesRows");
                });

            modelBuilder.Entity("ScontrinoSaga.Data.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvaialable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("ProductVat")
                        .HasColumnType("REAL");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ScontrinoSaga.Data.InvoiceRow", b =>
                {
                    b.HasOne("ScontrinoSaga.Data.Product", "InvoiceRowProduct")
                        .WithMany()
                        .HasForeignKey("InvoiceRowProductProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScontrinoSaga.Data.Invoice", "ParentInvoice")
                        .WithMany("InvoiceRows")
                        .HasForeignKey("ParentInvoiceInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceRowProduct");

                    b.Navigation("ParentInvoice");
                });

            modelBuilder.Entity("ScontrinoSaga.Data.Invoice", b =>
                {
                    b.Navigation("InvoiceRows");
                });
#pragma warning restore 612, 618
        }
    }
}
